package webtech.project.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.util.Objects;

@Entity
public class TrainingSessionMachine implements Training {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private int reps;
    private int sets;
    private int weight;
    private String machineName;
    private String comment;
//create table TRAINING_SESSION_MACHINE (id int generated by default as identity, comment varchar(255), machine_name varchar(255), reps int, sets int , weight int);
    public TrainingSessionMachine(int reps, int sets, String machineName, int weight, String comment){
    this.reps = reps;
    this.sets = sets;
    this.machineName = machineName;
    this.weight = weight;
    this.comment = comment;
    }

    public TrainingSessionMachine() {}

    @Override
    public int getReps() {
        return reps;
    }

    @Override
    public void setReps(int newReps) {
        this.reps = newReps;
    }

    @Override
    public int getSets() {
        return sets;
    }

    @Override
    public void setSets(int newSets) {
        this.sets = newSets;
    }

    @Override
    public String getComment() {
        return comment;
    }

    @Override
    public void setComment(String newComment) {
        this.comment = newComment;
    }

    public String getmachineName() {
        return machineName;
    }

    public void setMachineName(String newName) {
        this.machineName = newName;
    }

    public int getWeight() {
        return weight;
    }

    public void setWeight(int newWeight) {
        this.weight = newWeight;
    }


    @Override
    public boolean equals(Object o) {

        if (this == o)
            return true;
        if (!(o instanceof TrainingSessionMachine))
            return false;
        TrainingSessionMachine training = (TrainingSessionMachine) o;
        return Objects.equals(this.id, training.id) && Objects.equals(this.reps, training.reps)
                && Objects.equals(this.sets, training.sets) &&Objects.equals(this.comment, training.comment)
                && Objects.equals(this.machineName, machineName) && Objects.equals(this.weight, weight);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id, this.reps, this.sets, this.comment, this.machineName, this.weight);
    }

    //not completed
    @Override
    public String toString() {
        return "Employee{" + "id=" + this.id + ", name='" + this.machineName + '\'' + ", comment='" + this.comment + '\'' + ", weight= " + this.weight + '}';
    }

}
